### ISSUE TITLE
Update to the newest LTS

### ISSUE THREAD

**Issue by tillydray** [dino-/epub-tools#13]
The few updates we've done at work have been trivial, hoping 10.0 - 13.xx will be only marginally more difficult. Any known reason not to update?

**Comment by JasonMFry** [comment]
I forgot to run the tests, just ran them and I get

```
### Error in:   0:Format:51
user error (Text.Regex.Posix.String died: (ReturnCode 17,"illegal byte sequence"))
Cases: 96  Tried: 96  Errors: 1  Failures: 0
```

So don't merge this in yet :D
