### ISSUE TITLE
Failure to compile

### ISSUE THREAD

**Issue by iconoclasthero** [dino-/epub-tools#18]
I tried to compile on Ubuntu 18.04.  I assume I have stack since it executed...?

.
.
.
Once you have source, building the usual way:

      $ stack build
      $ stack test
      $ stack haddock

## Contact

Dino Morelli <[dino@ui3.info](mailto:dino@ui3.info)>
```
edt 1.05 pm  pwd: /dev/shm/cache/epub-tools-2.11 $ stack build
Downloaded lts-10.0 build plan.    
AesonException "Error in $.packages.cassava.constraints.flags['bytestring--lt-0_10_4']: Invalid flag name: \"bytestring--lt-0_10_4\""
edt 1.05 pm  pwd: /dev/shm/cache/epub-tools-2.11$ stack test
Downloaded lts-10.0 build plan.    
AesonException "Error in $.packages.cassava.constraints.flags['bytestring--lt-0_10_4']: Invalid flag name: \"bytestring--lt-0_10_4\""
edt 1.05 pm  pwd: /dev/shm/cache/epub-tools-2.11$ stack haddock
Downloaded lts-10.0 build plan.    
AesonException "Error in $.packages.cassava.constraints.flags['bytestring--lt-0_10_4']: Invalid flag name: \"bytestring--lt-0_10_4\""
```

**Comment by iconoclasthero** [comment]
```sudo apt install haskell-stack && stack upgrade && stack build

**Comment by dino-** [comment]
Maybe I should add something about `stack update` to the README file.

**Comment by iconoclasthero** [comment]
Once you have stack* source, building the usual way:

      $ stack upgrade && stack build
      $ stack test
      $ stack haddock

To install it in your user/local (e.g., ~/.local/bin) path directory:  
      $ stack install

To install to a global directory (e.g. /usr/local/bin):
      $ sudo stack install . --local-bin-path /usr/local/bin --allow-different-user

*stack must be installed, e.g., on Ubuntu:  
      $ sudo apt install haskell-stack

**Comment by iconoclasthero** [comment]
You can think of the 
`$ stack upgrade && stack build ` like `$ sudo apt update && sudo apt upgrade`
