### ISSUE TITLE
Fix Arch Linux packaging LICENSE file location issues

### ISSUE THREAD

**Issue by dino-** [dino-/epub-tools#30]

**Comment by m040601** [comment]
This should be easy, a simple "install"

```
install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
```

So it would end up in

```
/usr/share/licenses/epub-tools/LICENSE
```

You have all the info and simple tips in https://wiki.archlinux.org/title/PKGBUILD#Generic and related pages.



You also have README, docs, changelod etc. It would be nice if they were shipped in the tar.gz released and end up in someting like


```
/usr/share/docs/epub-tools/README
/usr/share/docs/epub-tools/Changelog
...
etc
```






pacman -Ql epub-tools



```
epub-tools /usr/
epub-tools /usr/bin/
epub-tools /usr/bin/epubmeta
epub-tools /usr/bin/epubname
epub-tools /usr/bin/epubzip
epub-tools /usr/share/
epub-tools /usr/share/epub-tools-2.11/
epub-tools /usr/share/epub-tools-2.11/doc/
epub-tools /usr/share/epub-tools-2.11/doc/LICENSE
```


Right now you have on the PKGBUILD

```
package() {
   cd ${srcdir}/${pkgname}-${pkgver}
   mkdir "${pkgdir}/usr"
   cp -r * "${pkgdir}/usr"
}
```

This "cp -r *" is uggly. You should use more the "install" (its' just like cp)


```
... 
cd xxx
install this
install that 
....

**Comment by dino-** [comment]
Thanks for the advice. I did move the `LICENSE` file to the proper location.
I did not change `cp -r` to `install` because I package the binary .tar.gz file in the shape already needed for Arch Linux. I use `install` already to create that shape before it gets to Arch packaging.
