### ISSUE TITLE
Release a new binary on github

### ISSUE THREAD

**Issue by m040601** [dino-/epub-tools#31]
Hi, thanks for this usefull tool. I've been using it for many years. 

Hope you can release a precompiled binary version on github soon.

I thought the project was dead, just by reading "2018" on the release page.

Thanks also for maintaining the PKGBUILD. for Archlinux, https://aur.archlinux.org/packages/epub-tools 

I noticed this "epub-tools" on Archlinux  is actually not a "source" PKGBUILD but a "-bin" PKGBUILD.

You should  also  take the chance and rename it to

```
epub-tools-bin
```

there on AUR.

Thanks in advance.

**Comment by dino-** [comment]
I'm the sole developer of this software, I doubt anyone else is going to make a source release of it on the AUR. Also, source AUR packages of Haskell projects kind of suck, so many dependencies to download for building. I may eventually release epub-tools as AppImage which I do for other projects already.
Anyway, I'll think about changing the AUR name, I do see that it may be clearer for users.

**Comment by m040601** [comment]
> I noticed this "epub-tools" on Archlinux is actually not a "source" PKGBUILD but a "-bin" PKGBUILD
> 


> source AUR packages of Haskell projects kind of suck, so many dependencies to download for building. 


My comment about this was not intended to "requesti" or "wish for" a source package. It was just because I saw a very old binary on AUR and lots of fresh activity on Github. I  fully 100% agree with you, and I am perfectly satisfied with the binary release on AUR.



What I dont agree with, and I am not satisfied is with the **name** of the tool on the  AUR  package. 

It should be changed from "epub-tools" to "epub-tools-bin".

 Actually It is not me, it's everyone else doing it and  the Arch guidelines, https://wiki.archlinux.org/title/AUR_submission_guidelines#Rules_of_submission

> Packages that use prebuilt [deliverables](https://en.wikipedia.org/wiki/Deliverable), when the sources are available, must use the -bin suffix.


.As you also seem to agree with me,


>  I'll think about changing the AUR name, I do see that it may be clearer for users.
